### ISSUE TITLE
Minimum bibtexparser version

### ISSUE THREAD

**Issue by galou** [t-wissmann/rofi-bibbrowser#2]
Hi, thanks for providing this tool (though I didn't manage to have it work yet).

I could be good to mention the minimum version of bibtexparser. Your script didn't work with the system-wide version 0.6.2 on Ubuntu 18.04. Some things worked better with version 1.0.1 from pip for Python3 but I still get some errors which may not be related to bibtexparser (cf. next issue).

**Comment by t-wissmann** [comment]
What error message do you get? I'm running python-bibtexparser in version 1.0.1 and I don't know whether one really needs at least 1.0.1, maybe older versions work as well.

**Comment by galou** [comment]
If I remember correctly, I had a wrong keyword `common_strings`.

**Comment by t-wissmann** [comment]
Hm ok. That sounds like a fairly recent thing, but I'm really not familiar with the python-bibtexbrowser development. Given that you got it running, I'll close this issue.
